name: Build & Deploy Spring app

on :
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Depoly Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

#      - name: Unit Tests
#        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --fie pom.xml